"""add priority, deadline, estimated_minutes, actual_minutes, timestamps to tasks

Revision ID: c10a22078407
Revises: b8c3f8375ea1
Create Date: 2026-07-09 13:26:19.700735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c10a22078407'
down_revision: Union[str, Sequence[str], None] = 'b8c3f8375ea1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('estimated_minutes', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('actual_minutes', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('priority', sa.String(), nullable=True))
    op.add_column('tasks', sa.Column('deadline', sa.DateTime(), nullable=True))
    op.add_column('tasks', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('tasks', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'updated_at')
    op.drop_column('tasks', 'created_at')
    op.drop_column('tasks', 'deadline')
    op.drop_column('tasks', 'priority')
    op.drop_column('tasks', 'actual_minutes')
    op.drop_column('tasks', 'estimated_minutes')
    # ### end Alembic commands ###
