from fastapi import APIRouter, Depends
from sqlalchemy.orm import Session, joinedload

from app.db.deps import get_db
from app.core.auth import get_current_user
from app.models.profile import NeuroProfile
from app.models.task import Task
from app.models.step import Step
from app.services.ai_service import generate_ai_steps

router = APIRouter(prefix="/ai", tags=["ai"])


@router.post("/generate-steps")
def ai_generate_steps(
    title: str,
    db: Session = Depends(get_db),
    user=Depends(get_current_user),
):

    # 1️⃣ Get user's support mode
    profile = (
        db.query(NeuroProfile)
        .filter(NeuroProfile.user_id == user.id)
        .first()
    )

    support_mode = profile.support_mode if profile else "adhd"

    # 2️⃣ Generate AI steps
    steps = generate_ai_steps(title, support_mode)

    # 3️⃣ Create Task
    task = Task(
        title=title,
        description="Generated by AI",
        user_id=user.id,
        is_completed=False,
    )

    db.add(task)
    db.commit()
    db.refresh(task)

    # 4️⃣ Create Step records
    for index, step_text in enumerate(steps):
        step = Step(
            content=step_text,
            order=index + 1,
            task_id=task.id,
            is_completed=False,
        )
        db.add(step)

    db.commit()

    # 5️⃣ Reload task WITH steps (important)
    task_with_steps = (
        db.query(Task)
        .options(joinedload(Task.steps))
        .filter(Task.id == task.id)
        .first()
    )

    return task_with_steps
